context:
  version: "2.12.2"

package:
  name: hello
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/hello/hello-${{ version }}.tar.gz
  sha256: 5a9a996dc292cc24dcf411cee87e92f6aae5b8d13bd9c6819b4c7a9dce0818ab

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - if: osx
      then: libiconv

tests:
  - script:
      - hello

about:
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Program providing model for GNU coding standards and practices
  homepage: https://www.gnu.org/software/hello/

extra:
  recipe-maintainers:
    - danielnachun
