context:
  version: "2.12.3"

package:
  name: hello
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/hello/hello-${{ version }}.tar.gz
  sha256: 0d5f60154382fee10b114a1c34e785d8b1f492073ae2d3a6f7b147687b366aa0

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - if: osx
      then: libiconv

tests:
  - script:
      - hello

about:
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Program providing model for GNU coding standards and practices
  homepage: https://www.gnu.org/software/hello/

extra:
  recipe-maintainers:
    - danielnachun
